# Generated by Django 3.2.8 on 2021-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('registrationNumber', models.PositiveIntegerField()),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfAdmission', models.DateField()),
                ('createdData', models.DateField()),
                ('lastModifiedData', models.DateField(auto_now=True)),
            ],
        ),
    ]
